### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by s1291** [LLNL/pyranda#34]
Hello,
Thank you for this project.
Is there a plan to migrate to Python 3?

Thanks

**Comment by tomstitt** [comment]
Hi @s1291 , based on the travis logs (https://travis-ci.org/LLNL/pyranda) it looks like master is building successfully with Python 3.5 and 3.6, what issues are you encountering?

**Comment by flow-phys** [comment]
Closing since no issue was raised.
