### ISSUE TITLE
Possibility of running 'PARCOP' only.

### ISSUE THREAD

**Issue by bgin** [LLNL/pyranda#63]
Hello

Is it possible to run parcop solver? only , i.e. without the python wrapping layer?
I'm mainly interested in such a usage as it will nicely fit my project requirements.

Best regards
Bernard

**Comment by bgin** [comment]
Seems nobody really cares to answer.

**Comment by flow-phys** [comment]
@bgin , yes.  This is possible and there is an example in the parcop directory and a makefile.  The miniApp.f90 is the main program which might serve as an example of who to use library.

**Comment by bgin** [comment]
It seems that pasted by me links somehow disappeared.
I'm providing the links here:

https://github.com/LLNL/pyranda/blob/master/pyranda/parcop/miniApp.f90#L204 <-- _**is this a direct call to solver?**_
Scondly -- how I can pass a boundary condition data?

Regards
Bernard Gingold

**Comment by flow-phys** [comment]
To see if I understand your question, are you wanting a hydro-dynamics solver in pure fortran?  The miniApp is not quite a full fluids solver but rather exercises the operators that a solver would use.  Its not turn key and you would need to develop your own full/expanded version of miniApp.f90.  

Does that make sense?

Calls to "div", "grad", "filter" are the solver components that parcop supplies but you'd need to write your own code to use these to make a hydro-solver.  One thing that is lacking in the miniApp.f90 example is the time integration.  Also, you'd need to define your own boundary conditions, etc natively in the fortran arrays.

Hopefully this helps clear things up.

-Britton

**Comment by bgin** [comment]
Hello @flow-phys 

`are you wanting a hydro-dynamics solver in pure fortran? The miniApp is not quite a full fluids solver but rather exercises the operators that a solver would use. Its not turn key and you would need to develop your own full/expanded version of miniApp.f90.`

Yes this is what I wanted to know!
Thank you for clearly explaining those slightly confusing (to me)  things.

Best regards

Bernard Gingold
